blank_issues_enabled: false
contact_links:
  - name: Questions / help
    url: https://github.com/nogcio/wrkr/discussions
    about: Please ask and answer usage questions here.
  - name: Security vulnerability report
    url: https://github.com/nogcio/wrkr/security/policy
    about: Please report security issues privately.
